* Elixir
** Introduction
Elixir is a pragmatic approach to functional programming. It values functional foundations and it focuses on developer productivity.

Concurrency is the backbone of Elixir software. Elixir is made to free you from antiquated concurrency mechanisms.

*** Functional language
A functional language lets us think in terms of functions that transform data. This transformation never mutates data. Instead, each application of a function potentially creates a new, fresh version of the data. This reduces the need for data-synchronization mechanisms.

*** Macros
Elixir empowers developers by providing macros. Elixir code is nothing more than data, and therefore can be manipulated via macros like any other value in the language.

*** Erlang VM
In the Erlang VM everything runs in tiny concurrent processes, each with its own state. All communication happens by message-passing, exchanging messages between different machines on the same network transparently by the VM, making it a perfect environment for building distributed software.

*** Functions are data transformers
Elixir lets us solve problems in the same way that Unix shell does. Rather than command-line utilities, we have functions. These functions we can string together as we please. The smaller and focused they are, the easier they're to reuse and combine.

If we want, we can make these functions run in parallel, Elixir has a simple but powerful mechanism for passing messages between them. This mechanism provides the potential to run millions of them on a single machine and have hundreds of these machines inter-operating.

Bruce Tate commented on this paragraph with this thought:
#+begin_quote
Most programmers treat threads and processes as a necessary evil; Elixir developers feel they are an important simplification. --- Bruce Tate
#+end_quote

*** Compile and Run
Elixir files will typically have the extension =.ex= or =.exs=. This is a convention--files ending in '.ex' are intended to be compiled into byte codes and then run, whereas those ending in =.exs.= are more like programs in scripting languages and are effectively interpreted at the source level.

When you write tests for Elixir programs, you'll see that the application files have =.ex= extensions, whereas the tests have =.exs= because we don't need to keep compiled versions of the tests lying around.

** Assignment
In Elixir, the equals sign is not an assignment. Instead it's like an assertion. It succeeds if Elixir can find a way of making the left-hand side equal the right-hand side. Elixir calls the ~=~ symbol the match operator.

*** Elixir can match true by binding the variable
In this case, the left-hand side is a variable and the right-hand side is an integer literal, so Elixir can make the match true by binding the variable ~a~ to value ~1~.

#+begin_src iex
iex> a = 1
1
iex> a + 3
4
#+end_src

**** Example of incorrect match
The second line of code, ~1 = a~. It's another match, and it passes. The variable =a= already has the value =1= (it was set in the first line), so what's on the left of the equals sign is the same as what's on the right, and the match succeeds. But the third line, ~2 = a~, raises an error. You might expect it to assign =2= to =a=, as that would make the match succeed, but Elixir will only change the variable of a variable on the left side of an equals sign and replace it with the =value= on the right side. The failing line of code is the same as ~2 = 1~, which causes an error.

#+begin_src iex
iex> a = 1
1
iex> 1 = 1
1
iex> 2 = a
(MatchError) no match of right hand side value: 1
#+end_src

**** More complex matches
Elixir looks for a way to make the value of the left side the same as the value of the right side. The left side is a list containing three variables, and the right is a list of three values, so the two sides could be made the same by setting the variables to the corresponding values.

Elixir calls this process /pattern matching/. A pattern (the left side) is matched if the values (the right side) have the same structure and if each term in the pattern can be matched to the corresponding term in the values. A literal value in the pattern matches that exact value, and a variable in the pattern matches by taking on the corresponding value.

#+begin_src iex
iex> list = [ 1, 2, 3 ]
[1, 2, 3]
iex> [a, b, c ] = list
[1, 2, 3 ]
iex> a
1
iex> b
2
iex> c
3
#+end_src

Another example.

#+begin_src iex
iex> list = [1, 2, [3, 4, 5]]
[1, 2, [3, 4, 5]]
iex> [a, b, c] = list
[1, 2, [3, 4 ,5]]
iex> a
1
iex> b
2
iex> c
[3, 4, 5]
#+end_src

Example with a pattern containing some values and variables

#+begin_src iex
iex> list = [1, 2, 3]
[1, 2, 3]
iex> [a, 2, b] = list
[1, 2, 3]
iex> a
a
iex> b
3
#+end_src

**** Ignore a Value with _ (Underscore)
If we don't need to capture a value doing a match, we could use the special variable =_=. This acts like a variable but immediately discards any value given to it in a pattern match.

#+begin_src iex
iex> [1, _, _] = [ 1, 2 ,3]
[1, 2, 3]
iex> [1, _, _] = [1, "cat", "dog"]
[1, "cat", "dog"]
#+end_src

**** Variables bind once (per Match)
Once a variable has been bound to a value in matching process, it keeps that value for the remainder of the match.

#+begin_src iex
iex> [a, a] = [1, 1]
[1, 1]
iex> a
1
iex> [b, b] = [1, 2]
(MatchError) no match of right hand side vlaue: [1, 2]
#+end_src

- The first expression in this example succeeds because =a= is initially matched with the first =1= on the right side.
- the second expression, the first =b= matches the =1=. But the second =b= corresponds to the value 2 on the right. =b= cannot have two different values, and so the match fails.

If you want to force Elixir to use the existing value of the variable in the pattern, then prefix it with =^= (a caret). In Elixir we call this the /pin operator/.

#+begin_src iex
iex> a = 1
1
iex> a = 2
2
iex> ^a = 1
(MatchError) no match of right hand side value: 1
#+end_src

This also works if the variable is a component of a pattern:

#+begin_src iex
iex> a = 1
1
iex> [^a, 2, 3] = [1, 2, 3]
[1, 2, 3]
iex> a = 2
2
iex> [^a, 2] = [1, 2]
(MatchError) no match of right hand side value: [1, 2]
#+end_src

**** Another way of looking at the Equals Sign
Elixir's pattern matching is similar to Erlang's. The main difference being that Elixir allows a match to reassign to a variable that was assigned in a prior match, whereas in Erlang a variable can be assigned only once.

Joe Armstrong, Erlang's creator, compares the equals sign in Erlang to that used in algebra. When you write the equation ~x = a + 1~, you are not assigning the value of ~a + 1~ to =x=. Instead you're simply asserting that the expressions =x= and ~a + 1~ have the same value. If you know the value of =x=, you can work out the value of =a=, and vice versa.

His point is that you had to unlearn the algebraic meaning of === when you first came across assignment in imperative programming languages.

** Immutability
In Elixir, all values are immutable. The most complex nested list, the database record - these things behave just like the simplest integer. Their values are all immutable.

In Elixir, once a variable references a list such as ~[1,2,3]~, you know it will always reference those same variables (until you rebind the variable). This makes concurrency a lot less dangerous.

But what if you need to add 100 to each element in ~[1,2,3]~? Elixir does it by producing a copy of the original, containing the new values. The original remains unchanged, and your operation will not affect any other code holding a reference to that original.

This fits with the idea that programming is about transforming data. When we update ~[1,2,3]~, we don't hack it in place. Instead we transform it into something new.

*** Performance implications of immutability
It would be easy to assume that enforcing immutability is inefficient. Because it would result in a lot of old values around to be garbage-collected.

**** Copying data
Common sense might dictate that all this copying of data is inefficient, the reverse is true. Because Elixir knows that existing data is immutable, it can reuse it, in part or as a whole, when building new structures.

The following code. It uses a new operator, ~[ head | tail ]~, which builds a new list with =head= as its first element and =tail= as the rest.

#+begin_src iex
iex> list1 = [3, 2, 1]
[3, 2, 1]
iex> list2 = [ 4 | list1 ]
[4, 3, 2, 1]
#+end_src

In most languages, =list2= would be built by creating a new list containing the values 4, 3, 2, and 1. The three values in =list1= would be copied into the tail of =list2=. And that would be necessary because =list1= would be mutable.

But Elixir knows =list1= will never change, so it simply constructs a new list with a head of 4 and a tail of =list4=.

**** Garbage collection
The other performance issue with a transformational language is that you quite often end up leaving old values unused when you create new values from them. This leaves a bunch of things using up memory on the heap, so garbage collection has to reclaim them.

Most modern languages have a garbage collector, and developers have grown to be suspicious of them, they can impact performance quite badly.

In Elixir you write your code using lots and lots of processes, and each process has its own heap. The data in your application is divided up between these processes, so each individual heap is much, much smaller than would have been the case if all the data had been in a single heap. As a result, garbage collection runs faster. If a process terminates before its heap becomes full, all its data is discarded, meaning no garbage collection is required.

**** Coding with immutable data
Once you accept the concept, coding with immutable data is surprisingly easy. You just have to remember that any function that transforms data will return a new copy of it. Thus, we never capitalize a string. Instead, we return a capitalized copy of a string.

#+begin_src iex
iex> name = "elixir"
"elixir"
iex> cap_name = String.capitalize name
"Elixir"
iex> name
"elixir"
#+end_src

In object-oriented languages you would most of the time solve it by saying ~name.capitalize()~. But in object-oriented languages, objects mostly have mutable state. When you make a call such as ~name.capitalize()~ you have no immediate indication whether you are changing the internal representation of the name, returning a capitalized copy, or both. There's plenty of scope of ambiguity.

In a functional language, we always transform data. We never modify it in place.

** Elixir basics
Elixir's built-in types:

- Value types:
  - Arbitrary-sized integers
  - Floating-point numbers
  - Atoms
  - Ranges
  - Regular expressions
- System types:
  - PIDs and ports
  - References
- Collection types:
  - Tuples
  - Lists
  - Maps
  - Binaries

Functions are a type too. They have their own chapter, following this one.

You might be surprised that list doesn't include things such as strings and structures. Elixir has them, but they are built using the basic types from the list.

There are some debate about whether regular expressions and ranges are value types. Technically they aren't - under the hood they are just structures. But its convenient to treat them as distinct types.

*** Value types
The value types in Elixir represent numbers, names, ranges, and regular expressions.

**** Integers
Integer literals can be written as decimal =1234=, hexadecimal =0xcafe=, octal =0o765=, and binary =0b1010=.

Decimal numbers may contain underscores these are often used to separate groups of three groups of three digits when writing large numbers, so one million could be written ~1_000_000~.

There is no fixed limit on the size of integers, their internal representation grows to fit their magnitude.

**** Floating-point numbers
Floating-point numbers are written using a decimal point. There must be at least one digit before and after the decimal point. An optional trailing exponent may be given. These are all valid floating-point literals:

- ~1.0~
- ~0.2456~
- ~0.314159e1~
- ~314159.0e-5~

Floats are IEEE 754 double precision, giving them about 16 digits of accuracy and a maximum exponent of around 10^308.

**** Atoms
=Atoms= are constants that represents something's name. We write them using a leading colon =:= which can be followed by an atom word or an Elixir operator. An atom word is a sequence of =UTF-8= letters (including combination-marks), digits, underscores, and at signs =@=. It may end with an exclamation point of a question mark. You can also create atoms containing arbitrary characters by enclosing the characters following the colon in double quotes. These are all atoms:

- ~:fred~
- ~:is_binary?~
- ~:var@2~
- ~:<>~
- ~:===~
- ~:"func/3"~
- ~:"long john silver"~

An atom's name is its value. Two atoms with the same name will always compare as equal, even if they were created by different applications on two computers separated by an ocean.

**** Ranges
~Ranges~ are represented as /start..end/, where =start= and =end= are integers.

**** Regular expressions
Elixir has regular-expression literals, written as =~r{regexp}= or =~r{regexp}opts=. Elixir regular expressions support is provided by =PCRE=, which basically provides a Perl 5-compatible syntax for patterns.

#+begin_src iex
iex> Regex.run ~r{[aeiou]}, "caterpillar"
["a"]
iex> Regex.scan ~r{[aeiou]}, "caterpillar"
[["a"], ["e"], ["i"], ["a"]]
iex> Regex.split ~r{[aeiou]}, "caterpillar"
["c", "t", "rp", "ll", "r"]
iex> Regex.replace ~r{[aeiou]}, "caterpillar", "*"
"c*t*rp*ll*r"
#+end_src

*** System types
These types reflect resources in the underlying =Erlang VM=.

**** PIDs and Ports
A =PID= is a reference to a local or remote process, and a =port= is a reference to a resource (typically external to the application) that you'll be reading or writing.

The =PID= of the current process is available by calling =self=. A new =PID= is created when you spawn a new process.

**** References
The function ~make_ref~ creates a global unique reference; no other reference will be equal to it.

*** Collection Types
Elixir collections can hold values of any type (including other collections).

**** Tuples
A =tuple= is an ordered collection of values. As with all Elixir data structures, once created a tuple cannot be modified.

You write a =tuple= between braces, separating the elements with commas.

- ~{ 1, 2 }~
- ~{ :ok, 42, "next" }~
- ~{ :error, :enoent }~

A typical Elixir =tuple= has two to four elements - any more and you should start looking at =maps= or =structs=.

You can use tuples in pattern matching:

#+begin_src iex
iex> {status, count, action} = {:ok, 42, "next"}
{:ok, 42, "next"}
iex> status
:ok
iex> count
42
iex> action
"next"
#+end_src

It is common for functions to return a tuple where the first element is the atom ~:ok~ if there were no errors. An example:

#+begin_src iex
iex> {status, file} = File.open("mix.exs")
{:ok, #PID<0.39.0>}
#+end_src

Because the file was successfully opened, the tuple contains an ~:ok~ status and a =PID=, which is how we access the contents.

A common practice is to write matches that assume success:

#+begin_src iex
iex> { :ok, file } = File.open("mix.exs")
{:ok, #PID<0.39.0>}
iex> {:ok, file} = File.open("non-existent-file")
(MatchError) no match of right hand side value: {:error, :enoent}
#+end_src

The second open failed, and returned a tuple where the first element was =:error=. This caused the match to fail, and the error message shows that the second element contains the reason =enoent= which is Unix-speak for "file does not exist".

**** Lists
A list is effectively a linked data structure. A list may either be empty or consist of a head and a tail. The head contains a value and the tail is itself a list.

Because of their implementation, lists are easy to traverse linearly, but they are expensive to access in random order, because you have to traverse them to the =nth= element. It is always cheap to get the head of a list and to extract the tail of a list.

Lists have one other performance characteristic. All Elixir data structures are immutable, that means once a list has been made, it will never be changed. So, if we want to remove the head form a list, leaving just the tail, we never have to copy the list. Instead we can return a pointer to the tail.

Elixir has some operators that work specifically on lists:

#+begin_src iex
iex> [1, 2, 3] ++ [ 4, 5, 6]   # concatenation
[1, 2, 3, 4, 5, 6]
iex> [1, 2, 3, 4] -- [2, 4]      # difference
[1, 3]
iex> 1 in [1, 2, 3, 4]            # membership
true
iex> "wombat" in [1, 2, 3 ,4]
false
#+end_src

***** Keyword lists
Because we often need simple lists of key/value pairs, Elixir gives us a shortcut. If we write

#+begin_src elixir
[name: "Dave", city: "Dallas", likes: "Programming"]
#+end_src

Elixir converts it into a list of two-value tuples:

#+begin_src elixir
[{:name, "Dave"}, {:city, "Dallas"}, {:likes, "Programming"}]
#+end_src

Elixir allows us to leave off the square brackets if a keyword list is the last argument in a function call. Thus,

#+begin_src elixir
DB.save record, [{:use_transaction, true}, {:logging, "HIGH"}]
#+end_src

can be written more cleanly as

#+begin_src elixir
DB.save record, use_transaction: true, logging: "HIGH"
#+end_src

We can also leave off the brackets if a keyword list appears as the last item in any context where a list of values is expected.

#+begin_src iex
iex> [1, fred: 1, dave: 2]
[1, {:fred, 1}, {:dave, 2}]
iex> {1, fred: 1, dave: 2}
{1, [fred: 1, dave: 2]}
#+end_src

**** Maps
A map is a collection of key/value pairs. Map literal looks like this:

#+begin_src elixir
%{key => value, key => value}
#+end_src

Examples of maps:

#+begin_src iex
iex> state = %{"AL" => "Alabama", "WI" => "Wisconsin"}
%{"AL" => "Alabama", "WI" => "Wisconsin"}

iex> responses = %{{:error, :enoent} => :fatal, {:error, :busy} => :retry}
%{{:error, :busy} => :retry, {:error, :enoent} => :fatal}

iex> colors = %{:red => 0xff0000, :green => 0x00ff00, :blue => 0x0000ff}
%{blue: 255, green: 65280, red: 16711680}
#+end_src

In the first case the keys are strings, in the second they're tuples, and in the third they're atoms. Although typically all the keys in a map are the same type, that isn't required.

Why do we have both maps and keyword lists? Maps allow only one entry for a particular key, whereas keyword lists allow the key to be repeated. Maps are efficient (particularly as they grow), and they can be used in Elixir's pattern matching.

In general, use keyword lists for things such as command-line parameters and passing around options, and use maps when you want an associative array.

***** Accessing a map
You extract values form a map using the key. The square-bracket syntax works with all maps:

#+begin_src iex
iex> states = %{"AL" => "Alabama", "WI" => "Wisconsin"}
%{"AL" => "Alabama", "WI" => "Wisconsin"}
iex> states["AL"]
"Alabama"
iex> states["TX"]
nil

iex> response_types = %{ {:error, :enoent} => fatal, {:error, :busy} => retry}
%{ {:error, :enoent} => fatal, {:error, :busy} => retry}
iex> response_types[{:error,:busy}]
:retry
#+end_src

If the keys are atoms, you can also use a dot notation:

#+begin_src iex
iex> colors = %{red: 0xff0000, green: 0x00ff00, blue: 0x0000ff}
%{blue: 255, green: 65280, red: 16711680}
iex> colors[:red]
16711680
iex> colors.green
65280
#+end_src

You'll get a =KeyError= if there's no matching key when you use the dot notation.

**** Binaries
Sometimes you need to access data as a sequence of bits and bytes. For example, the headers in JPEG and MP3 files where a single byte may encode two or three separate values.

Elixir supports this with the binary data type. Binary literals are enclosed between << and >>.

The basic syntax packs successive integers into bytes:

#+begin_src iex
iex> bin = <<1, 2>>
<<1, 2>>
iex> byte_size bin
2
#+end_src

Binaries are important because Elixir uses them to represent =UTF= strings. They're arcane because, at least initially you're unlikely to use them directly.

**** Dates and Times
The =Date= type holds a year, a month, and a reference to the ruling calendar.

#+begin_src iex
iex> d1 = Date.new(2018, 12, 25)
{:ok, ~D[2018-12-25]}
iex> {:ok, d1} = Date.new(2018, 12, 25)
{:ok, ~D[2018-12-25]}
iex> d2 = ~D[2018-12-25]
~D[2018-12-25]
iex> d1 == d2
true
iex> Date.day_of_week(d1)
2
iex> date.add(d1, 7)
~D[2019-01-01]
#+end_src

The sequences =~D= are examples of Elixir's =sigils= . They are a way of constructing literal values.

**** Names, source files, conventions, operators
Elixir identifiers must start with a letter or underscore, optionally followed by letters, digits, and underscores. Examples of variables

- ~name~
- ~_age~
- ~_42~

Module, record, protocol, and behavior names start with an uppercase letter, and are =BumpyCase=. All other identifiers start with a lowercase letter or an underscore, and by convention use underscores between words. If the first character is an underscore, Elixir doesn't report a warning if the variable is unused in a pattern match or function parameter list.

By convention, source files use two-characters indention for nesting and they use spaces, not tabs, to achieve this.

Comments start with a hash sign ~#~ and run to the end of a line.

***** Truth
Elixir has three special values related to =Boolean= operations: ~true~, ~false~, and ~nil~. ~nil~ is treated as false in =Boolean= contexts. In most contexts, any value other than ~false~ or ~nil~ is treated as true. We sometimes refer to this as =truthy= as opposed to ~true~.

***** Operators
Elixir has a very rich set of operators. Here's a subset we'll use in this book:

Comparison operators
- ~a === b~  strict equality
- ~a !== b~  strict inequality
- ~a ==  b~  value equality
- ~a !=  b~  value inequality
- ~a >   b~  normal comparison
- ~a >=  b~
- ~a <   b~
- ~a <=  b~

Elixir is less strict than many languages when it comes to comparisons, as you can compare values of different types. If the types are the same or are compatible for example ~3 > 2~ or ~3.0 < 5~, the comparison uses natural ordering.

****** Boolean operators
These operators expect true or false as their first argument.

#+begin_src elixir
a or b     # true if a is true; otherwise b
a and b    # false if a is false; otherwise b
not a      # false if a is true; true otherwise
#+end_src

****** Relaxed boolean operators
These operators take arguments of any type. Any value apart from ~nil~ or ~false~ is interpreted as true.

#+begin_src elixir
a || b    # a if a is truthy; otherwise b
a && b    # b if a is truthy; otherwise a
!a        # false if a is truthy; otherwise true
#+end_src

****** Arithmetic operators
~+-*/ div rem~. Integer division yields a floating-point result Use ~div(a,b)~ to get an integer. ~rem~ is the =remainder operator=. It is called a function ~rem(11,3) => 2~. It differs from normal modulo operations in that the result will have the same sign as a function first argument.


****** Join operators
#+begin_src elixir
binary1 <> binary2 # concatenates two binaries
list ++ list2      # concatenates two lists
list1 -- list2     # removes elements of list 2 from a copy of list 1
#+end_src

****** The in operator
#+begin_src elixir
a in enum # Tests if a is included in enum
#+end_src

** Thanks to
[[https://pragprog.com/titles/elixir16/programming-elixir-1-6/][Programming Elixir 1.6]]
